### ISSUE TITLE
APNS for Mail (and Calendar, Contacts) on Mojave

### ISSUE THREAD

**Issue by essandess** [matthewpowell/pushnotify#1]
I just spoke with Enterprise support, who told me that it will still be possible to create push notification certificates at https://identity.apple.com/pushcert/.

However, there is no Apple documentation on how to create APNS certificates for the open source [Mail/Contacts/Calendar alternatives](
https://support.apple.com/en-hk/HT208312).

It appears that going forward it may be possible to replicate APNS certificate creation by hand (once per year) using Keychain Access to generate the correctly configured certificates and a CSR that can be uploaded to https://identity.apple.com/pushcert/ for signing.

These certificates could then be used in the configuration of a self-hosted mail and calendar server that is patched to support APNS.

Does anyone know how to create a correctly formatted APNS certificate from Keychain Access that can be signed by Apple? My own certificates at https://identity.apple.com/pushcert/ look like this. If this approach works, I expect that one would need to generate APNS certificates for apns:com.apple.calendar, apns:com.apple.contact, and apns:com.apple.mail. This would be easy to script once the details are determined.
```
server.domain.tld - apns:com.apple.calendar
server.domain.tld - apns:com.apple.contact
server.domain.tld - apns:com.apple.mail
server.domain.tld - apns:com.apple.mgmt
server.domain.tld - apns:com.apple.alerts
```

**Comment by essandess** [comment]
Replicating what I see on my server, the APNS certificate configuration details are (with a random Version 1 UUID generated [here](https://www.uuidgenerator.net/version1)):

| Field    | Value                                                                                           |
|------|----------------------------------------------------|
|User ID | `com.apple.mail.XServer.674783d8-cbd0-11e8-a8d5-f2801f1b9fd1 ` |
|Common Name | `APSP:674783d8-cbd0-11e8-a8d5-f2801f1b9fd1 ` |
|Key Usage           | Encrypt, Verify, Derive |
|Extension>Key Usage>Critical           | NO |
|Extension>Key Usage>Digital Signature           | Digital Signature |
|Extension>Extended Key Usage>Critical           | NO |
|Extension> Extended Key Usage>Purpose #1           | Client Authentication |

There is an "identity preference" in the Keychain named `apns:com.apple.mail` (with same "Where" field) with "Preferred Certificate" `APSP:674783d8-cbd0-11e8-a8d5-f2801f1b9fd1 `, also in the Keychain.

I presume the other fields are added or modified by the signing authority. I do not see how or where the specific domain information `server.domain.tld - apns:com.apple.mail` is added, or whether this is necessary.

**Comment by matthewpowell** [comment]
CSRs submitted to https://identity.apple.com/pushcert/ need to be formatted specially with a vendor signature. It's not obvious whether MDM push and mail push are interchangeable, but if they are then https://github.com/grinich/mdmvendorsign looks like an interesting starting point. You may need to be signed up as an enterprise developer ($299/year) to get the required signing key.

For the time being it is still possible to generate and renew certificates using the Server app in macOS versions prior to Mojave. I'd imagine that will remain a viable option for a few more years, although it won't work forever.

**Comment by essandess** [comment]
See here for some successful reports of people doing exactly what you suggest: 
https://github.com/st3fan/dovecot-xaps-daemon/issues/46#issuecomment-469708103

**Comment by essandess** [comment]
This is working now. See #2.
